dist: precise
language: node_js
node_js:
  - 6
  - 8
cache:
  directories:
  - node_modules
install: true
script:
 - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master